[package]
name="tinywasm-types"
version.workspace=true
description="TinyWasm types"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true
rust-version.workspace=true

[dependencies]
log={workspace=true, optional=true}
rkyv={version="0.7", optional=true, default-features=false, features=["size_32", "validation"]}
bytecheck={version="0.7", optional=true, default-features=false}

[features]
default=["std", "logging", "archive"]
std=["rkyv?/std", "bytecheck?/std"]
archive=["dep:rkyv", "dep:bytecheck"]
logging=["dep:log"]
